- hosts: postgres_master
  become: yes
  vars_files:
    - common-vars.yaml
    - master-vars.yaml
  roles:
    - role: postgresql
- hosts: minio
  become: yes
  vars_files:
    - minio-vars.yaml
  roles:
    - role: minio
- hosts: postgres_slave
  become: yes
  vars_files:
    - common-vars.yaml
    - slave-vars.yaml
  roles:
    - role: postgresql
    - role: postgresql-slave
