- hosts: postgres_master
  become: yes
  vars_files:
    - ./vars/pg_commons.yaml
    - ./vars/pg_master.yaml
  roles:
    - role: anxs.postgresql
- hosts: postgres_slave
  become: yes
  vars_files:
    - ./vars/pg_commons.yaml
    - ./vars/pg_slave.yaml
  roles:
    - role: anxs.postgresql
    - role: postgresql-slave
- hosts: postgres_slave_of_slave
  become: yes
  vars_files:
    - ./vars/pg_commons.yaml
    - ./vars/pg_slave_of_slave.yaml
  roles:
    - role: anxs.postgresql
    - role: postgresql-slave
- hosts: minio
  become: yes
  vars_files:
    - ./vars/minio.yaml
  roles:
    - role: atosatto.minio
