- name: Compose the Walg download url
  set_fact:
    _walg_download_url: "https://github.com/wal-g/wal-g/releases/download/{{ walg_version }}/wal-g.linux-amd64.tar.gz"

- name: Download the walg executable
  get_url:
    url: "{{ _walg_download_url }}"
    dest: "{{ walg_script_location }}"
    owner: "root"
    group: "root"
    mode: 0755
  register: _download_executable
  until: _download_executable is succeeded
  retries: 5
  delay: 2

- name: Extract Walg Executable
  unarchive:
    src: "{{ _download_executable.dest }}"
    dest: "{{ walg_script_location }}"
    owner: "postgres"
    group: "postgres"
    mode: 0755
    remote_src: yes

- name: Remove downloaded walg tar
  file:
    path: "{{ _download_executable.dest }}"
    state: absent

- name: Generate the base_backup script
  template:
    src: base_backup.sh.j2
    dest: "{{ walg_script_location }}/walg_base_backup.sh"
    owner: "postgres"
    group: "postgres"
    mode: 0755

- name: Generate the archive_command script
  template:
    src: archive_command.sh.j2
    dest: "{{ walg_script_location }}/walg_archive_command.sh"
    owner: "postgres"
    group: "postgres"
    mode: 0755

