# Default config for Prometheus Postgresql Exporter
prometheus_exporter_dir: "/opt/prometheus/exporters"
prometheus_exporter_dist_dir: "{{ prometheus_exporter_dir }}/dist"
prometheus_exporter_service_mgr: "{{ ansible_service_mgr }}"
prometheus_exporter_ansible_packages:
  - python-selinux
prometheus_exporter_service_packages: []

postgres_exporter_user: postgres
postgres_exporter_user_manage: false
postgres_exporter_group: "{{ postgres_exporter_user }}"
postgres_exporter_group_manage: false

postgres_exporter_version: "0.8.0"
postgres_exporter_checksum: "sha256:272ed14d3c360579d6e231db34a568ec08f61d2e163cf111e713929ffb6db3f5"

postgres_exporter_dist_dir: "{{ prometheus_exporter_dist_dir }}"
postgres_exporter_dist: postgres_exporter_v{{ postgres_exporter_version }}_linux-amd64
postgres_exporter_url: "https://github.com/wrouesnel/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/{{ postgres_exporter_dist }}.tar.gz"
postgres_exporter_program: "{{ prometheus_exporter_dir }}/postgres_exporter"
postgres_exporter_home: "/var/lib/postgresql"
postgres_exporter_home_manage: false
postgres_exporter_datasource: "user=postgres host=/var/run/postgresql/ sslmode=disable"
postgres_exporter_queries: "queries.yaml"
postgres_exporter_flags:
  - '--auto-discover-databases'
  - '--extend.query-path={{ postgres_exporter_home }}/queries.yml'

postgres_exporter_config_file: /etc/default/postgres_exporter
postgres_exporter_pid_path: "/var/run"
postgres_exporter_log_path: "/var/log/postgres_exporter"

postgres_exporter_service_manage: true
postgres_exporter_service_enable: true
postgres_exporter_service_state: started
postgres_exporter_service_notify: true
