postgresql_version: 9.5
wal_g_version: v0.2.14
golang_version: 1.13
wal_g_cron_timespec: "10 04 * * *"

postgresql_cluster_name: main
postgresql_varlib_directory_name: "postgresql"
wal_g_postgres_db_location: "/var/lib/{{ postgresql_varlib_directory_name }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}"

wal_g_postgres_user: postgres
