postgresql_replication_enable: False
walg_support_enable: False

postgresql_version: 12

postgresql_replication_master_host: ""
postgresql_replication_master_port: 5432
postgresql_replication_user: rep
postgresql_replication_password: localhost
postgresql_replication_trigger_file: /tmp/postgresql.trigger.5432

postgresql_service_name: "postgresql"
postgresql_bin_directory: /usr/bin

postgresql_cluster_name: main
postgresql_varlib_directory_name: "postgresql"
postgresql_data_directory: "/var/lib/{{ postgresql_varlib_directory_name }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}"

walg_version: v0.2.14
walg_script_location: /usr/local/bin

walg_aws_endpoint: ""

walg_s3_prefix: ""
walg_aws_access_key_id: ""
walg_aws_secret_access_key: ""
walg_aws_region: "ap-southeast-1"


